# Copy this file to bots-secret.yaml and replace with your actual credentials
# Note: For first-time setup, use the web interface instead of manually creating this file
POSTGRES_USER=your_postgres_user  
POSTGRES_PASSWORD=your_postgres_password