apiVersion: v1
kind: Service
metadata:
  name: bots-dirmonitor
spec:
  ports:
  - name: service
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: health
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    app: bots-dirmonitor
---
apiVersion: v1
kind: Service
metadata:
  name: bots-jobqueue
spec:
  ports:
  - name: service
    port: 28082
    protocol: TCP
    targetPort: 28082
  - name: health
    port: 8882
    protocol: TCP
    targetPort: 8882
  selector:
    app: bots-jobqueue
---
apiVersion: v1
kind: Service
metadata:
  name: bots-webserver
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: health
    port: 8881
    protocol: TCP
    targetPort: 8881
  selector:
    app: bots-webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-dirmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bots-dirmonitor
  template:
    metadata:
      labels:
        app: bots-dirmonitor
    spec:
      containers:
      - command:
        - python3.12
        - bots-dirmonitor.py
        envFrom:
        - configMapRef:
            name: bots-config
        - secretRef:
            name: bots-secrets
        image: ghcr.io/cedayhoff/bots
        livenessProbe:
          httpGet:
            path: /health
            port: 8883
          initialDelaySeconds: 30
          periodSeconds: 10
        name: bots-dirmonitor
        ports:
        - containerPort: 8888
        - containerPort: 8883
        readinessProbe:
          httpGet:
            path: /health
            port: 8883
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-jobqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bots-jobqueue
  template:
    metadata:
      labels:
        app: bots-jobqueue
    spec:
      containers:
      - command:
        - python3.12
        - bots-jobqueueserver.py
        envFrom:
        - configMapRef:
            name: bots-config
        - secretRef:
            name: bots-secrets
        image: ghcr.io/cedayhoff/bots
        livenessProbe:
          httpGet:
            path: /health
            port: 8882
          initialDelaySeconds: 30
          periodSeconds: 10
        name: bots-jobqueue
        ports:
        - containerPort: 28082
        - containerPort: 8882
        readinessProbe:
          httpGet:
            path: /health
            port: 8882
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bots-webserver
  template:
    metadata:
      labels:
        app: bots-webserver
    spec:
      containers:
      - command:
        - python3.12
        - bots-webserver.py
        envFrom:
        - configMapRef:
            name: bots-config
        - secretRef:
            name: bots-secrets
        image: ghcr.io/cedayhoff/bots
        livenessProbe:
          httpGet:
            path: /health
            port: 8881
          initialDelaySeconds: 30
          periodSeconds: 10
        name: bots-webserver
        ports:
        - containerPort: 8080
        - containerPort: 8881
        readinessProbe:
          httpGet:
            path: /health
            port: 8881
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret
