apiVersion: v1
kind: Service
metadata:
  name: bots-webserver
spec:
  selector:
    app: bots-webserver
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: health
      protocol: TCP
      port: 8881
      targetPort: 8881
