apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-jobqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bots-jobqueue
  template:
    metadata:
      labels:
        app: bots-jobqueue
    spec:
      containers:
      - name: bots-jobqueue
        image: ghcr.io/cedayhoff/bots
        ports:
        - containerPort: 28082
        - containerPort: 8882
        envFrom:
          - configMapRef:
              name: bots-config
          - secretRef:
              name: bots-secrets
        command: ["python3.12", "bots-jobqueueserver.py"]
        volumeMounts:
        - name: bots-db-volume
          mountPath: /app/bots/botssys/sqlitedb
        - name: bots-config-volume
          mountPath: /app/bots/config
        - name: bots-data-volume
          mountPath: /app/bots/botssys/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8882
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8882
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: bots-db-volume
        persistentVolumeClaim:
          claimName: bots-db-pvc
      - name: bots-config-volume
        persistentVolumeClaim:
          claimName: bots-config-pvc
      - name: bots-data-volume
        persistentVolumeClaim:
          claimName: bots-data-pvc
      imagePullSecrets:
        - name: ghcr-secret
