apiVersion: v1
kind: Service
metadata:
  name: bots-dirmonitor
spec:
  selector:
    app: bots-dirmonitor
  ports:
    - name: service
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: health
      protocol: TCP
      port: 8883
      targetPort: 8883